### ISSUE TITLE
A small problem with the site's theme/color

### ISSUE THREAD

**Issue by thanhnguyen2187** [khanhicetea/khanhicetea#1]
Hi! Really interesting writing there! I just have one problem with it's accessibility: the color for your quotes is the same as the background color, which makes reading impossible unless I select the text.

![image](https://github.com/user-attachments/assets/7f6896db-55a0-43ab-88f3-fd436f5c958f)

I dearly hope you can fix that!

Thanks!

**Comment by khanhicetea** [comment]
Yah, thank you for reporting tiny but important issue :( 

I'm light mode user, so never try dark mode, I don't think this ever exists :( Just added tricky a tailwind class "dark:prose-invert" to hot-fix the main content div)

Thanks, have a nice day man!
